title: CrankGPT
description: A hand-crankable, fully offline voice AI. Built at Squeez Labs.

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Just-the-Docs options
color_scheme: light
search_enabled: false
heading_anchors: true
footer_content: ""

callouts:
  highlight-orange:
    color: yellow

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - raw_outline.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - _config.dev.yml
